### ISSUE TITLE
Ampersand (&) in mod name truncates mods after it

### ISSUE THREAD

**Issue by rykugur** [PepeCitron/projectzomboid-server#10]
This might be more a limitation of docker than anything specific to this image - I am still an intermediate docker user.

While trying to debug why Brita's weapon mod wasn't loading on our server, I found out that a mod I had installed (and forgotten to disable (oops)) had an Ampersand in the mod name, and the `Mods=` line in the server ini file was being truncated, so any mod after that wasn't being loaded.

`Mods=....,Mod,Mod,FB41 AR&SMG Rebalance,Mod,Mod...`

would turn in to:

`Mods=....,Mod,Mod,FB41 AR`

Note: I am using a `.env` file to configure my mods/workshop ids, but this also happened if I put the mod names/ids directly in the `docker-compose.yml` file. We ended up removing/not needing the mod, so not a big deal for us anymore, but figured I'd report it.

**Comment by PepeCitron** [comment]
Fix in ba246234
