### ISSUE TITLE
start-server.sh

### ISSUE THREAD

**Issue by tehface** [PepeCitron/projectzomboid-server#12]
Connecting anonymously to Steam Public...OK
pzserver  | Waiting for client config...OK
pzserver  | Waiting for user info...OK
pzserver  | ERROR! Failed to install app '380870' (Missing file permissions)
pzserver  | Creating symlink for config folder...
pzserver  | Updating server.ini...
pzserver  | Launching server...
pzserver  | sh: 1: ./start-server.sh: not found
pzserver exited with code 0

**Comment by tehface** [comment]
Connecting anonymously to Steam Public...OK
pzserver  | Waiting for client config...OK
pzserver  | Waiting for user info...OK
pzserver  | ERROR! Failed to install app '380870' (Missing file permissions)
pzserver  | Creating symlink for config folder...
pzserver  | Updating server.ini...
pzserver  | Launching server...
pzserver  | sh: 1: ./start-server.sh: not found
pzserver exited with code 0

**Comment by tehface** [comment]
ran docker in admin etc etc

**Comment by tehface** [comment]
found another repo with a working docker version

**Comment by rykugur** [comment]
This started happening for me as well, albeit randomly. @PepeCitron has this image/project been abandoned?

**Comment by v9999** [comment]
> found another repo with a working docker version

which repo? I'm having the same issue...
