### ISSUE TITLE
entry.sh: line 23: [: : integer expression expected

### ISSUE THREAD

**Issue by GHaxZ** [PepeCitron/projectzomboid-server#13]
When running the docker container I get the following error:

`/data/scripts/entry.sh: line 23: [: : integer expression expected`

I think this is happening because the `entry.sh` script is comparing a string using `-eq`, which should only be used for comparing strings.

I have both tried leaving the `SERVER_BRANCH` env variable to its default value and explicitly setting it to `SERVER_BRANCH=""`, but I get the error in both cases.

Maybe I am doing something wrong on my side, but I'm not really sure what that would be.

**Comment by PepeCitron** [comment]
I mistakenly modified the condition for `SERVER_BRANCH` in the last fix.
I've just made a fix in a061c9ec
Thanks for your issue
