### ISSUE TITLE
How to load mods?

### ISSUE THREAD

**Issue by kexue-z** [PepeCitron/projectzomboid-server#3]
i want to load `ATA_Bus` mod for example

add in config in  `config/Server/server.ini`
```ini
Mods=ATA_Jeep
```
disable steam in `server-file/ProjectZomboid64.json`
```json
{
  "vmArgs": 
      "-Dzomboid.steam=0"
}
```
finally add mod file at `config/mods/ATA_Bus`

```
config/mods
└── ATA_Bus
    ├── changelog.txt
    ├── media
    │   ├── lua
    │   ├── models_X
    │   ├── scripts
    │   ├── textures
    │   └── ui
    ├── mod.info
    ├── poster.png
    └── preview.png
```

Is this correct?

**Comment by PepeCitron** [comment]
Personally, I use the mods via the workshop and I haven't tested without. I use this line in server.ini
```
WorkshopItems=
Mods=
```

**Comment by kexue-z** [comment]
I tested adding workshop mod will cause some problem like: 
- client mod update to latest version but server mod reminds old version. it need to restart the server to update.
- for some condition, updating mods will break the save. so all the players need to start over.

**Comment by an-aessid** [comment]
Updating the server and the mods by restarting the instance works for me without data loss, the saves stay intact. Adding mods afterwards is also working out for me.

I'm also using the mentioned `WorkshopItems` and `Mods` config options of the server.ini file. E.g.
```
WorkshopItems=2778991696
# List of Workshop Mods must be separated by semicolon
Mods=Hydrocraft
```
