### ISSUE TITLE
I am getting the error server has port 16262 closed. Performance may be affected

### ISSUE THREAD

**Issue by uacaman** [PepeCitron/projectzomboid-server#7]
I am getting the error server has port 16262 closed. Performance may be affected. Is there a option to map this port?

**Comment by tautv** [comment]
As of `v41.77`, ports have changed from zomboid. It no longer requires 8766 and 8767. 
Two game depended ports are now `16261/udp` and `16262/udp` (Direct Connection Port).
Looks like this repo uses the older style for them. You can fork this repo and add few changes yourself.
# .Dockerfile:
add `SERVER_PORT_2="16262" \` after the `SERVER_PORT="16261" \`:
>ENV STEAMPORT1="8766" \
    STEAMPORT2="8767" \
    SERVER_NAME="server" \
    SERVER_PASSWORD="" \
    SERVER_ADMIN_PASSWORD="pzadmin" \
    SERVER_PORT="16261" \
    SERVER_PORT_2="16262" \
    SERVER_BRANCH="" \
    SERVER_PUBLIC="false" \
    SERVER_PUBLIC_NAME="Project Zomboid Docker Server" \
    SERVER_PUBLIC_DESC="" \
    SERVER_MAX_PLAYER="16" \
    RCON_PORT="27015" \
    RCON_PASSWORD="" \
	UID="1000" \
	GID="1000"

add `EXPOSE $SERVER_PORT_2/udp` under `EXPORT $SERVER_PORT/udp`:
>EXPOSE $STEAMPORT1/udp
EXPOSE $STEAMPORT2/udp
EXPOSE $SERVER_PORT/udp
EXPOSE ${RCON_PORT}


# docker-compose.yaml:
add ` - "16262:16262/udp" under ` - "16261:16261/udp"`:
>    ports:
      - "8766:8766/udp"
      - "8767:8767/udp"
      - "16261:16261/udp"
      - "16262:16262/udp"

Apart from being a mess, it should work.

I'm working on my own implementation, but it's not ready yet. Check on my repos in few weeks, I'll change the repo to Public as soon as it's ready.

**Comment by Mansonjr** [comment]
@tautv Tried your solution without success :( I'm still getting the same error when i connect.

even with log correct messages:

LOG  : Network     , 1680613783397> 107,654,667> Server is listening on port 16261 (for Steam connection) and port 16262 (for UDPRakNet connection)

did all the changes you mentioned, and checked twice there are now firewalls (In that terms, host is now open in DMZ Host mode without any protecction, (Never recommended))

**Comment by PepeCitron** [comment]
Fix 890b03e66ad91d0e768ff9045526785a9480b314
